// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyYHUPYs_IRKHOiyne4QAQnI_iJP3ll6s',
    appId: '1:100383000655:web:b34c7276343ed4d65cc23a',
    messagingSenderId: '100383000655',
    projectId: 'teamflutterproject01',
    authDomain: 'teamflutterproject01.firebaseapp.com',
    storageBucket: 'teamflutterproject01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1jR0hOd-NGZEfjizoALZx-vhnven8Tik',
    appId: '1:601360980310:android:cf2dd1ea82d940d7d3def7',
    messagingSenderId: '601360980310',
    projectId: 'project-287a6',
    storageBucket: 'project-287a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjlOVFSbFElaOu2tnRjGwgZqPE5Zil8vg',
    appId: '1:100383000655:ios:514eb1bea97c02495cc23a',
    messagingSenderId: '100383000655',
    projectId: 'teamflutterproject01',
    storageBucket: 'teamflutterproject01.firebasestorage.app',
    iosBundleId: 'com.example.teamFlutterProject01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjlOVFSbFElaOu2tnRjGwgZqPE5Zil8vg',
    appId: '1:100383000655:ios:514eb1bea97c02495cc23a',
    messagingSenderId: '100383000655',
    projectId: 'teamflutterproject01',
    storageBucket: 'teamflutterproject01.firebasestorage.app',
    iosBundleId: 'com.example.teamFlutterProject01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyYHUPYs_IRKHOiyne4QAQnI_iJP3ll6s',
    appId: '1:100383000655:web:805b75114ea0e1f45cc23a',
    messagingSenderId: '100383000655',
    projectId: 'teamflutterproject01',
    authDomain: 'teamflutterproject01.firebaseapp.com',
    storageBucket: 'teamflutterproject01.firebasestorage.app',
  );

}